#!/bin/sh
device_name=/dev/sdb1
case $1 in
  start)
    if `mount | grep "^${device_name}" > /dev/null`;then
      /sbin/blockdev --setra 16384 ${device_name}
    else
      exit 0
    fi
 
    unset device_name
    ;;
esac
